### ISSUE TITLE
automatically halt all machines on shutdown

### ISSUE THREAD

**Issue by nostalgicdodo** [lanayotech/vagrant-manager#121] opened 2015-11-19 10:33 UTC
I forget to halt the machines most of the time. A dialog prompting to halt the machines would be helpful. If they could automatically halted, that would be awesome.

**Comment by esszett** [comment] 2015-12-02 15:23
Same here, I agree.

**Comment by maces** [comment] 2015-12-03 07:52
duplicate of #90

**Comment by chriswayoub** [comment] 2017-11-06 20:24
This feature has been implemented in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)

**Closed by chriswayoub** 2017-11-06 20:24 UTC
Labels: feature request
