### ISSUE TITLE
Incompatible With Homestead 2?

### ISSUE THREAD

**Issue by mikebronner** [lanayotech/vagrant-manager#76] opened 2015-03-09 13:44 UTC
It was working with Laravel Homestead 1.x great, but after upgrading to Laravel Homestead 2.x, there seem to be some issues. Commands no longer work (e.g. up, provision) and status is not correctly reported (always red).

**Comment by vesper8** [comment] 2015-04-19 13:15
Can I ask if you figured out what the problem was? Interested in this

**Comment by mikebronner** [comment] 2015-04-19 16:43
No solution yet ... I haven't used it since I made the post. :(

**Comment by chuckreynolds** [comment] 2015-04-28 06:56
idk if this is my issue but... can't seem to get vagrant-manager to work with homestead 2.0.17 either. 

current versions: 
- homestead 2.0.17
- vagrant 1.7.2
- zsh 5.0.5

from terminal i can homestead up and it all runs fine but while it's running vagrant-manager looks like this:
![screen shot 2015-04-27 at 23 15 17](https://cloud.githubusercontent.com/assets/46185/7363774/8be7eb26-ed33-11e4-9260-36d9f1b0ee50.png)
Clicking on Up loads it all then says 
```
A VirtualBox machine with the name 'homestead' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```
everything I can tell is in ~/.composer/vendor/laravel/homestead/
which homestead goes to: .composer/vendor/bin/homestead but those are fwd'd to that ../laravel/ dirs

**Comment by delphyne** [comment] 2015-05-13 00:34
It is possible that this issue can be addressed by https://github.com/lanayotech/vagrant-manager/issues/84, which deals with the spawned bash processes not acting as login shells (and as a result not seeing your PATH, only the system default PATH)

**Comment by chuckreynolds** [comment] 2015-05-13 05:52
Hmm @delphyne - sounds plausible but I'm not going to pretend to understand how to test that so... I hope somebody smarter than me can :+1:

**Comment by delphyne** [comment] 2015-05-13 16:46
You can build the app from my PR in #84, and see if it fixes your problem, or hopefully the maintainers will accept my PR and you can get the next version when it comes out.

**Comment by amitailanciano** [comment] 2015-05-24 21:28
[release 2.4.0](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.0) should fix this issue

**Closed by amitailanciano** 2015-05-24 21:28 UTC

**Comment by chuckreynolds** [comment] 2015-05-25 03:11
with my newly setup homestead environment the 2.4.0 release does seem to be functioning as intended. thank you gents. cheers.

**Comment by mikebronner** [comment] 2015-05-27 16:43
I am getting the same error as @chuckreynolds mentioned above with 2.4.0 on an existing Homestead 0.2.6 vm. @delphyne mentioned Bash issues ... I'm using ZSH, so my bash instance won't know where homestead is, ZSH would though. Is there a way to configure VM to use ZSH instead of Bash?

**Comment by pjebs** [comment] 2015-06-15 00:58
I'm using release 2.4.1.

Doesn't work with laravel Homestead

**Comment by pjebs** [comment] 2015-06-15 00:59
The error I get when I try to up the vm is:

Vagrant failed to initialize at a very early stage:

The directory Vagrant will use to store local environment-specific
state is not accessible. The directory specified as the local data
directory must be both readable and writable for the user that is
running Vagrant.

Local data directory: /Users/Me/.composer/vendor/laravel/homestead/.vagrant

**Comment by pjebs** [comment] 2015-06-15 00:59
So I'm stuck having to type in the command "homestead up" to get up the VM.

**Comment by kingsloi** [comment] 2016-02-02 13:26
Did anyone ever find a fix for this?
