### ISSUE TITLE
Updated to 2.4.2, no longer detects VMs automatically, status doesn't work.

### ISSUE THREAD

**Issue by nroca** [lanayotech/vagrant-manager#105] opened 2015-08-06 07:50 UTC
Updated from 2.4.2 today from what I believe was 2.4.0. 

Vagrant Manager no longer shows my VMs in the dropdown. I have to add them manually. Upon adding them manually, the status does not reflect the state of the VM, rather it shows them all red. 'vagrant global-status' in cli shows status' properly.

**Comment by amitailanciano** [comment] 2015-08-06 14:01
If you could give this debug build a shot and post the results I'd really appreciate it, it will log some debugging information in your system log, which you can view in the Console application or in your terminal.

https://www.dropbox.com/s/b6v3ccrirn43wy3/Vagrant%20Manager%20%282.4.2%20Debug%29.app.zip?dl=1

**Comment by nroca** [comment] 2015-08-06 16:19
'vagrant global-status --prune' had an error etc.

The error was the following:
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/PixelPusher/Development/project.com/Vagrantfile
Line number: 17
Message: RuntimeError: ansible/group_vars/development file not found. Please set `ANSIBLE_PATH` in Vagrantfile
```

I use roots.io for all my wordpress projects. So I am bringing up the issue with them. As I am certain my projects are setup correctly. Also I have no problem running the projects manually.

**Comment by amitailanciano** [comment] 2015-08-06 17:17
I figured that was the case, I'll close this issue as the issue is not with Vagrant Manager; I will however be updating the app to show an error when `vagrant global-status --prune` fails

**Closed by amitailanciano** 2015-08-06 17:17 UTC

**Comment by nroca** [comment] 2015-08-06 17:46
For future reference this is what solved my issue:

> @nathan_roca I think that the vagrant global-status command is reading Vagrantfile info from a different directory context than the original Vagrantfiles, so the relative path ANSIBLE_PATH = 'ansible' is failing.
> Could you edit your Vagrantfile like below to make it an absolute path and see if it resolves the issue?
ANSIBLE_PATH = File.join(__dir__, 'ansible')
