### ISSUE TITLE
I'm not a code writer - need help with an error displayed in the log

### ISSUE THREAD

**Issue by magiclens57** [lanayotech/vagrant-manager#156] opened 2017-04-08 18:52 UTC
I pasted the error message into Google and found a person had the same? as mine.
4/8/17 2:39:47.400 PM Console[467]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable

Can anyone tell me what this means? Is it serious enough to be corrected..if so, how?
Millions of thanks!

**Comment by amitailanciano** [comment] 2017-06-14 08:34
duplicate of #134

**Closed by amitailanciano** 2017-06-14 08:34 UTC
