### ISSUE TITLE
Vagrant Manager 2.4.2 crashes immediately on load; 2.4.1 is fine.

### ISSUE THREAD

**Issue by incredimike** [lanayotech/vagrant-manager#104] opened 2015-08-04 19:28 UTC
Upgraded to 2.4.2. Vagrant Manager starts and immediately exits. Reverted back to 2.4.1 and it works perfectly. Not sure how I can help debug the issue?

OSX Yosemite 10.10.4 MBP Retina

**Comment by andrew40** [comment] 2015-08-04 20:04
Upgraded to 2.4.2 and it loads ok with no errors but does not pick up any of my previous vagrant machines. List is blank?

**Comment by amitailanciano** [comment] 2015-08-04 20:17
@incredimike can you provide your crash log?
@andrew40 if you run `vagrant global-status --prune` in your terminal, does it list any machines?

**Comment by andrew40** [comment] 2015-08-04 20:20
I get this message if i run within a vagrant folder such as VVV and the same if i run outside folder ie root..

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/andrewwilkinson/VagrantWP/hgv/Vagrantfile
Line number: 299
Message: Errno::ENOENT: No such file or directory - ./provisioning/default-install.yml

**Comment by andrew40** [comment] 2015-08-04 20:20
![screenshot 2015-08-04 21 20 55](https://cloud.githubusercontent.com/assets/158435/9071709/ac667e0e-3aee-11e5-918f-2f3afc018ffa.png)

**Comment by amitailanciano** [comment] 2015-08-04 20:25
Just did a few tests and it appears as though if you have an error in one of your the Vagrantfiles that is discovered by `vagrant global-status --prune` command, vagrant crashes with that error instead of displaying the normal `global-status` output; at hotfix will come soon, thanks for reporting the issue

**Comment by andrew40** [comment] 2015-08-04 20:30
What error would it pick up in the vagrant file, maybe we could track it down?

**Comment by amitailanciano** [comment] 2015-08-04 20:31
well your error looks like this one:

```
Path: /Users/andrewwilkinson/VagrantWP/hgv/Vagrantfile
Line number: 299
Message: Errno::ENOENT: No such file or directory - ./provisioning/default-install.yml
```

that file does not exist.

**Comment by andrew40** [comment] 2015-08-04 20:32
yes i gathered and realised after i wrote it, sorry! too fast to hit return!!

That file however does exist.

**Comment by amitailanciano** [comment] 2015-08-04 20:34
@incredimike if Vagrant Manager is crashing completely, your issue is different than @andrew40's

@andrew40 that error is not related to Vagrant Manager, I'm willing to wager if you just cd into that `hgv` directory and run `vagrant status` in your terminal, you will get the same error

**Comment by andrew40** [comment] 2015-08-04 20:37
I'll take your wager and raise you five ;)

vagrant status
Current machine states:

hgv                       running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.

**Comment by andrew40** [comment] 2015-08-04 20:40
ok i'm getting new messages now..

vagrant status
Current machine states:

hgv                       running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.
Andrews-MacBook-Pro:hgv andrewwilkinson$ agrant global-status --prune
-bash: agrant: command not found
Andrews-MacBook-Pro:hgv andrewwilkinson$ agrant global-status --prune
-bash: agrant: command not found
Andrews-MacBook-Pro:hgv andrewwilkinson$ vagrant global-status --prune
id       name     provider   state   directory
--------------------------------------------------------------------------
37cc137  default  virtualbox aborted /Users/andrewwilkinson/vagrant-local
3ce679f  hgv      virtualbox running /Users/andrewwilkinson/VagrantWP/hgv
6eff655  vccw.dev virtualbox saved   /Users/andrewwilkinson/vccw

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
/Users/andrewwilkinson/VagrantWP/hgv/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/andrewwilkinson/VagrantWP/hgv/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here

but there is no boxes showing in the vagrant window
![screenshot 2015-08-04 21 40 38](https://cloud.githubusercontent.com/assets/158435/9072149/6adb705e-3af1-11e5-83b9-c6d99c78eeae.png)

**Comment by incredimike** [comment] 2015-08-04 21:32
@andrew40 Next time start a new issue instead of hijacking an unrelated bug report. :/

@amitailanciano The "V" icon appears in the "top bar" (forget the proper name), looks like it's loading, then immediately disappears. I don't get the OSX crash report modal.

**Comment by andrew40** [comment] 2015-08-04 21:34
Next time tell me at the beginning before answering my comments :/ sorry

**Comment by incredimike** [comment] 2015-08-04 21:42
Ok I found the crash logs. Want me to post the entire thing here?

https://www.dropbox.com/s/wedqpuzgxljkacp/Vagrant%20Manager_2015-08-04-143912_Mikes-MBP-smash.crash?dl=0

**Comment by amitailanciano** [comment] 2015-08-04 21:46
@incredimike that's great, I'll go through it this evening and see what I can find

**Comment by incredimike** [comment] 2015-08-04 21:51
@amitailanciano Great! Hope it's a quick fix!

**Comment by amitailanciano** [comment] 2015-08-05 03:51
@incredimike can you possibly post the output of `vagrant global-status --prune` for me?

**Comment by fretwellian** [comment] 2015-08-05 14:07
@amitailanciano Hi, I am experiencing the same as incredimike there doesn't seem to be alot useful when I post the output:...

id       name    provider   state    directory                                  
--------------------------------------------------------------------------------
5fd90a8  default virtualbox poweroff /Users/xxx/Documents/xxx   
2c90b56  default virtualbox poweroff /Users/xxx/Documents/xxx 
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"

**Comment by amitailanciano** [comment] 2015-08-06 03:30
@fretwellian can you provide me with a crash log? I want to verify that it's the same issue as @incredimike. 

Also, can you post the _exact_ output? I'm assuming you don't actually have an `xxx` user :) or perhaps email it to me if you don't feel comfortable posting it here? You can email it to tai@lanayo.com

I just need the exact output of `vagrant global-status --prune` to help get to the bottom of it, it sounds like it might be some edge case parsing that output; that is the only place `substringWithRange` is used in the whole project and that's the method in the stack trace from @incredimike that it bailed on

**Comment by sophistifunk** [comment] 2015-08-06 05:39
I'm guessing my problem is the same, I get this when running ```/Applications/Vagrant\ Manager.app/Contents/MacOS/Vagrant\ Manager```

```
2015-08-06 15:36:36.566 Vagrant Manager[97612:3606847] An uncaught exception was raised
2015-08-06 15:36:36.567 Vagrant Manager[97612:3606847] -[__NSCFString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 72
2015-08-06 15:36:36.567 Vagrant Manager[97612:3606847] (
	0   CoreFoundation                      0x00007fff8f7fb03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9765176e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8f7faeed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff8f707418 -[__NSCFString substringWithRange:] + 136
	4   Vagrant Manager                     0x0000000104996a01 Vagrant Manager + 84481
	5   Vagrant Manager                     0x000000010498c37f Vagrant Manager + 41855
	6   Vagrant Manager                     0x0000000104987106 Vagrant Manager + 20742
	7   libdispatch.dylib                   0x00007fff91909323 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff91904c13 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff9190788f _dispatch_root_queue_drain + 935
	10  libdispatch.dylib                   0x00007fff91915fe4 _dispatch_worker_thread3 + 91
	11  libsystem_pthread.dylib             0x00007fff8cbea637 _pthread_wqthread + 729
	12  libsystem_pthread.dylib             0x00007fff8cbe840d start_wqthread + 13
)
2015-08-06 15:36:36.567 Vagrant Manager[97612:3606847] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 72'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8f7fb03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9765176e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8f7faeed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff8f707418 -[__NSCFString substringWithRange:] + 136
	4   Vagrant Manager                     0x0000000104996a01 Vagrant Manager + 84481
	5   Vagrant Manager                     0x000000010498c37f Vagrant Manager + 41855
	6   Vagrant Manager                     0x0000000104987106 Vagrant Manager + 20742
	7   libdispatch.dylib                   0x00007fff91909323 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff91904c13 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff9190788f _dispatch_root_queue_drain + 935
	10  libdispatch.dylib                   0x00007fff91915fe4 _dispatch_worker_thread3 + 91
	11  libsystem_pthread.dylib             0x00007fff8cbea637 _pthread_wqthread + 729
	12  libsystem_pthread.dylib             0x00007fff8cbe840d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by amitailanciano** [comment] 2015-08-06 05:50
@sophistifunk can you post the output of `vagrant global-status --prune` for me to debug with?

**Comment by sophistifunk** [comment] 2015-08-06 05:54
Sure, it's not very interesting though. XXXXXXXXX is a valid directory containing a working Vagrantfile

```
> vagrant global-status --prune
id       name    provider   state   directory
-------------------------------------------------------------------------
d75c456  default virtualbox running /Users/josh/XXXXXXXXX

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```

**Comment by amitailanciano** [comment] 2015-08-06 06:02
Can you post it in its entirety or email it to me at tai@lanayo.com?

**Comment by sophistifunk** [comment] 2015-08-06 06:13
```
> cat Vagrantfile
# settings to pass into provisioning scripts
informix_host_ip = '10.0.0.99'
informix_hostname = 'ifxdb01s1'
db_password = 'XXXXXX'

Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-c6-soe.box"
  config.vm.box_url = "https://nexus.companyname.com.au/service/local/artifact/maven/redirect?r=releases&g=au.com.companyname&a=vagrantbox-c6-soe&e=box&v=RELEASE"
  config.vm.hostname = informix_hostname

  # your SOE companyname folder (required)
  config.vm.synced_folder "~/env-companyname-soe", "/soe"

  config.vm.network :private_network, :ip => informix_host_ip

  config.vm.provision "shell", path: 'puppet.sh',    privileged: false, args: [ informix_hostname, informix_host_ip ]
  config.vm.provision "shell", path: 'provision.sh', privileged: true,  args: [ informix_hostname, informix_host_ip, db_password ]

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 1
  end
end
```

**Comment by amitailanciano** [comment] 2015-08-06 06:36
Sorry I wasn't clear, I meant the global status command, including the directory path

**Comment by sophistifunk** [comment] 2015-08-06 06:51
Sorry, our project is currently "secret". Stupid, but I don't write the cheques.

**Comment by sophistifunk** [comment] 2015-08-06 06:52
There's nothing special about the directory though, no wacky characters or even spaces.

**Comment by sophistifunk** [comment] 2015-08-06 06:55
Also, I just tried destroying the VM (it's fresh so it's only build time I've lost), and get the same exception.

**Comment by amitailanciano** [comment] 2015-08-06 14:01
Please give this debug build a shot and post the results, it will log some debugging information in your system log, which you can view in the Console application or in your terminal.

https://www.dropbox.com/s/b6v3ccrirn43wy3/Vagrant%20Manager%20%282.4.2%20Debug%29.app.zip?dl=1

**Comment by incredimike** [comment] 2015-08-06 17:29
```
$ vagrant global-status --prune
/Users/mike/code/xxxxx-roadmap/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx-tilt/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
/Users/mike/code/xxxxx-falcon-fibre/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx-roadmap/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
/Users/mike/code/xxxxx-international-v1/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx-falcon-fibre/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
/Users/mike/code/xxxxx-falcon-v2/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx-international-v1/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
/Users/mike/code/xxxxx-international-v2/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx-falcon-v2/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
/Users/mike/code/xxxxx/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx-international-v2/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
id       name         provider   state    directory                               
----------------------------------------------------------------------------------
cbec7ab  xxxxxxxx     virtualbox aborted  /Users/mike/code/xxxxx-tilt              
6373e2b  xxxxxxxxxxxx virtualbox poweroff /Users/mike/code/xxxxx-roadmap          
1f2dde1  xxxxxx       virtualbox saved    /Users/mike/code/xxxxx-falcon-fibre     
6a343c9  xxxx         virtualbox poweroff /Users/mike/code/xxxxx-international-v1 
03c46c5  xxxxxxxx     virtualbox aborted  /Users/mike/code/xxxxx-falcon-v2        
1ad289c  xxxx         virtualbox running  /Users/mike/code/xxxxx-international-v2 
30e33d3  xxxxxxxx     virtualbox running  /Users/mike/code/xxxxx               
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
/Users/mike/code/xxxxx-international-v2/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
/Users/mike/code/xxxxx/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
```

**Comment by incredimike** [comment] 2015-08-06 17:32
Debug version runs without failing, but does not find any vagrant instances. I assume that's due to all the errors in the `vagrant global-status --prune` output

**Comment by amitailanciano** [comment] 2015-08-06 17:33
can you post the logged messages from your syslog? you can view them in the Console app

**Comment by incredimike** [comment] 2015-08-06 17:46
Okay. I googled for a bit. Seems like it's a vagrant issue?

all of my vagrant files begin with the following:

```
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  [...]
end
```

On one Vagrantfile I commented out the constant "VAGRANTFILE_API_VERSION" and replaced the configure command loop with `Vagrant.configure(2) do |config|`. After that, the errors related to that file do not appear. I will try updating all files and report back.

**Comment by incredimike** [comment] 2015-08-06 17:47
```
2015-08-06 10:47:30.358 AM Vagrant Manager[7495]: 'vagrant global-status --prune' full output


Agent pid 7507
id       name         provider   state    directory                               
----------------------------------------------------------------------------------
cbec7ab  tedxtilt     virtualbox aborted  /Users/mike/code/tedx-tilt              
6373e2b  telusroadmap virtualbox poweroff /Users/mike/code/telus-roadmap          
1f2dde1  falcon       virtualbox saved    /Users/mike/code/telus-falcon-fibre     
6a343c9  tiv1         virtualbox poweroff /Users/mike/code/telus-international-v1 
03c46c5  falconv2     virtualbox aborted  /Users/mike/code/telus-falcon-v2        
1ad289c  tiv2         virtualbox running  /Users/mike/code/telus-international-v2 
30e33d3  footshot     virtualbox running  /Users/mike/code/footshot               
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
Killing SSH-Agent
2015-08-06 10:47:30.358 AM Vagrant Manager[7495]: Bad Index: directoryIndex -- line scanned: 'Agent pid 7507'
2015-08-06 10:47:30.358 AM Vagrant Manager[7495]: Bad Index: nameIndex -- line scanned: 'Agent pid 7507'
2015-08-06 10:47:30.358 AM Vagrant Manager[7495]: Bad Index: providerIndex -- line scanned: 'Agent pid 7507'
2015-08-06 10:47:30.359 AM Vagrant Manager[7495]: Bad Index: stateIndex -- line scanned: 'Agent pid 7507'
```

**Comment by amitailanciano** [comment] 2015-08-06 17:50
Perfect, that solves it; I'll push out a hotfix this evening, thanks to everyone for the help debugging

**Comment by amitailanciano** [comment] 2015-08-06 17:58
@andrew40 see the last post in this issue thread, https://github.com/lanayotech/vagrant-manager/issues/105 I believe that should help you resolve your issue

**Comment by incredimike** [comment] 2015-08-06 18:02
FYI, my shell is zsh (oh my zsh) which runs/outputs a bunch of junk when it starts, e.g. `eval (ssh-agent)`. That's probably apparent, but tying up loose ends.

**Comment by amitailanciano** [comment] 2015-08-07 18:10
should be resolved by [release 2.4.3](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.3)

**Comment by incredimike** [comment] 2015-08-07 20:06
2.4.3 still crashes for me.

```
2015-08-07 1:05:38.170 PM Vagrant Manager[12414]: An uncaught exception was raised
2015-08-07 1:05:38.170 PM Vagrant Manager[12414]: -[__NSCFString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 68
2015-08-07 1:05:38.170 PM Vagrant Manager[12414]: (
	0   CoreFoundation                      0x00007fff9bbf603c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9632376e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9bbf5eed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff9bb02418 -[__NSCFString substringWithRange:] + 136
	4   Vagrant Manager                     0x000000010d7bfa01 Vagrant Manager + 84481
	5   Vagrant Manager                     0x000000010d7b537f Vagrant Manager + 41855
	6   Vagrant Manager                     0x000000010d7b0106 Vagrant Manager + 20742
	7   libdispatch.dylib                   0x00007fff9524a323 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff95245c13 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff9524888f _dispatch_root_queue_drain + 935
	10  libdispatch.dylib                   0x00007fff95256fe4 _dispatch_worker_thread3 + 91
	11  libsystem_pthread.dylib             0x00007fff94860637 _pthread_wqthread + 729
	12  libsystem_pthread.dylib             0x00007fff9485e40d start_wqthread + 13
)
2015-08-07 1:05:38.170 PM Vagrant Manager[12414]: *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 68'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9bbf603c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9632376e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9bbf5eed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff9bb02418 -[__NSCFString substringWithRange:] + 136
	4   Vagrant Manager                     0x000000010d7bfa01 Vagrant Manager + 84481
	5   Vagrant Manager                     0x000000010d7b537f Vagrant Manager + 41855
	6   Vagrant Manager                     0x000000010d7b0106 Vagrant Manager + 20742
	7   libdispatch.dylib                   0x00007fff9524a323 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff95245c13 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff9524888f _dispatch_root_queue_drain + 935
	10  libdispatch.dylib                   0x00007fff95256fe4 _dispatch_worker_thread3 + 91
	11  libsystem_pthread.dylib             0x00007fff94860637 _pthread_wqthread + 729
	12  libsystem_pthread.dylib             0x00007fff9485e40d start_wqthread + 13
)
2015-08-07 1:05:38.184 PM com.apple.xpc.launchd[1]: (com.apple.ReportCrash[12475]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
2015-08-07 1:05:38.614 PM com.apple.xpc.launchd[1]: (lanayo.Vagrant-Manager.113064[12414]) Service exited due to signal: Abort trap: 6
2015-08-07 1:05:38.646 PM ReportCrash[12475]: Saved crash report for Vagrant Manager[12414] version 2.4.3 (2.4.3) to /Users/mike/Library/Logs/DiagnosticReports/Vagrant Manager_2015-08-07-130538_Mikes-MBP-smash.crash
```

**Comment by bronzeiii** [comment] 2015-08-07 20:44
Same here too.. 2.4.3 crashes on startup..

**Comment by amitailanciano** [comment] 2015-08-07 23:04
Looks like I missed a Regex option `NSRegularExpressionAnchorsMatchLines` for grabbing the header line, I'll push out a (hopefully) final hotfix release this evening after some further testing, my apologies for the previous hotfix

**Comment by amitailanciano** [comment] 2015-08-08 01:28
Just want to verify that the problem has been resolved before I put out another release, here's the upcoming 2.4.4 build, let me know if there are still issues:

https://www.dropbox.com/s/hfgey5y0d4jid1i/Vagrant%20Manager%202.4.4b.app.zip?dl=0

**Comment by sneakybeaky** [comment] 2015-08-08 07:54
@amitailanciano I was seeing the same issues with the 2.4.3 release, but your 2.4.4b build works fine.

**Comment by amitailanciano** [comment] 2015-08-08 14:49
Great, glad to hear that, [release 2.4.4](https://github.com/lanayotech/vagrant-manager/releases/tag/2.4.4]) is now available

**Closed by amitailanciano** 2015-08-08 14:49 UTC
Labels: bug
